# Generated by Django 3.2.7 on 2021-09-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_id'),
        ('post', '0004_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='post.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_by',
            field=models.ManyToManyField(blank=True, to='account.Account'),
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='post.comment')),
                ('likes_by', models.ManyToManyField(blank=True, to='account.Account')),
            ],
        ),
    ]
