# Generated by Django 3.2.7 on 2021-09-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_id'),
        ('post', '0005_auto_20210922_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='account.Account'),
        ),
    ]
