# Generated by Django 3.2.7 on 2021-09-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_replycomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='reply_text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
