# Generated by Django 3.2.7 on 2021-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210922_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like_count',
            new_name='coment_likes_count',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='likes_count',
            new_name='reply_likes_count',
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
