# Generated by Django 3.2.7 on 2021-09-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='coment_likes_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_likes_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='reply_likes_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
